### ISSUE TITLE
貌似这几天又不更新了哦

### ISSUE THREAD

**Issue by hl668** [WencoChen/MineEarth#11]
作者你好，首先感谢你这个壁纸软件很好用。然后这几天的话已经快3天桌面壁纸地球画面不更新了，看了下向日葵官网是一直在更新的。麻烦作者你看下怎么回事

**Comment by cofe123** [comment]
作者好像是武汉的，应该是哪个储存满了没人清理，希望作者没事~~~

**Comment by wksama** [comment]
> 作者好像是武汉的，应该是哪个储存满了没人清理，希望作者没事~~~

谢谢🙂，确实是湖北人😷。你说对了，是储存库满了，刚清理了，测试可用，感谢反馈🙏

**Comment by wksama** [comment]
感谢 大家一直都在使用，也谢谢大家热心反馈，过段时间我会写个程序定时清理仓库。在家办公脑子好像没那么多好点子了，原定的更新计划也搁置了起来。说过要做的东西都会做的，待我修整一下状态，咱们下一个版本再见！

**Comment by hl668** [comment]
> 感谢大家一直都在使用，也谢谢大家热心反馈，过段时间我会写一个程序定时清理仓库。在家办公脑子好像没那么多好点子了，原定的更新计划也搁置了起来。说过要做的东西都会做的，待我修整一下状态，咱们下一个版本再见！

哦哦，原来是在湖北，那作者你注意安全哈，坐等你的下一个版本。希望软件运行在后台占内存和CPU不大，然后能自动更新桌面壁纸就行了，不用那些花里胡巧的功能，简约小巧实用的就可以了~ 最后再次感谢作者这个软件~期待你的回归
