### ISSUE TITLE
问一下怎么卸载掉这个程序..

### ISSUE THREAD

**Issue by leocodelab** [WencoChen/MineEarth#3]

**Comment by westfly** [comment]
怎么退出，在trash下也米有看到呢。
进程中也没有。

**Comment by westfly** [comment]
找到了，打开任务管理左下角的 
![image](https://user-images.githubusercontent.com/1453169/71567724-2a6af800-2afc-11ea-9329-ff9508c2bb16.png)
然后在如下终止界面找到windows.exe 即可。
![image](https://user-images.githubusercontent.com/1453169/71567711-0effed00-2afc-11ea-8a58-fcb66e017ce8.png)

**Comment by wksama** [comment]
首先，程序不存在安装，自然就没有卸载这个概念了
1. 如果之前将程序放到了开机启动文件夹，就需要将它从开机文件夹移出来，不然开机就会自己启动
2. 打开任务管理器，找到进程，结束掉就行了（仔细找）
3. 如果任务管理器找不到，说明程序没在运行，自己手动换你想要的壁纸就行了

最后，这个在帖子中都有解释过，这类与程序本身无关的问题就不要在这里问了吧，感谢🙏
