### ISSUE TITLE
win10 x64 问题

### ISSUE THREAD

**Issue by HOOKDLL** [WencoChen/MineEarth#4]
_, _, err = systemParametersInfo.Call(
		uintptr(0x0020), //需要修改为20才能正常设置壁纸
		uintptr(0x0000), //0
		uintptr(unsafe.Pointer(filenameUTF16)),
		uintptr(0x01|0x02), //1|2
	)

**Comment by wksama** [comment]
我家里和公司的电脑都是win10 x64啊，并没有出现无法设置壁纸的问题，目前就是有几个x86的反映程序启动不了，等我后续再测试一下吧
