### ISSUE TITLE
算力占 %100 CPU 问题

### ISSUE THREAD

**Issue by HOOKDLL** [WencoChen/MineEarth#5]
建议使用 github.com/robfig/cron/v3 分钟内检查不消费算力,不会造成占用CPU过高问题
个人修改实例
Cron V3 has been released!

To download the specific tagged release, run:
go get github.com/robfig/cron/v3@v3.0.0

my code

package main

import (
    "fmt"
	"os"
	"time"
	"github.com/robfig/cron/v3"
)

const (
	URL   = "https://gitee.com/wencochen/No.8-Sunflower/raw/master/earth.png"
	SCALE = 0.618
	CACHE = false
)

var (
	FilePath  string
	cacheDir = os.TempDir() + string(os.PathSeparator) + "wallpaper_cache"
)

func run() {
	c := cron.New()
	
	c.AddFunc("@every 1m", func() { 
		
		fmt.Println("@every 1m ok") 
		
		wallpaper := NewWallpaper()
		
		wallpaper.Exec()
		
		})
		
	c.Start()
}

func main() {
	
	wallpaper := NewWallpaper()
	
	wallpaper.Exec()
	
	go run()
	
for  {
	time.Sleep(90000000000000000000)//等待很久一个的时间,为了不让程序退出
	fmt.Println("Sleep 90000000000000000000 ok") 	
}

}

**Comment by wksama** [comment]
嗯，感谢反馈，这种情况在我电脑上并没有出现过啊，目前程序问题主要是内存占用没有调至最优，当时写的时候主要想着代码尽量不用三方包，使程序尽可能小一点，后续功能更新会将这方面着重考虑的。
