### ISSUE TITLE
图片已经不自动更新了

### ISSUE THREAD

**Issue by hl668** [WencoChen/MineEarth#6]
前天开始图片就不自动更新了 ，服务器出问题了把。作者你看一下

**Comment by wksama** [comment]
刚去[源网站](http://himawari8.nict.go.jp/)看了一下，与我的桌面对比了一下，一下是对比截图：

官网截图：
![image](https://user-images.githubusercontent.com/38133076/72235085-261a0100-360b-11ea-8e7c-0a5fd81581e3.png)

码云及桌面截图：
![image](https://user-images.githubusercontent.com/38133076/72235111-4b0e7400-360b-11ea-988c-b7a274155a1c.png)

另外如果抓取图片有任何异常，我的服务器都会向我发送一封邮件，这是我这几天收到的邮件：
![image](https://user-images.githubusercontent.com/38133076/72235182-9de82b80-360b-11ea-902a-c779ebf9a644.png)

综上，应该是源网站的图片没有更新，你可以自行对比一下。

**Comment by hl668** [comment]
首先感谢作者回复，去了向日葵官网看了下，官网的图片是在更新的，时间轴往回拉，图片一直在变化的。但是更新的图片貌似不对，或者说是时间对不上，按照官网现在更新的图片又看不出来是不是大洋洲地区。按道理现在白天，大洋洲地区地球应该能全部显示出来，而官网的就像现在这样只显示了一半，作者你的软件应该没问题。问题在官网，谢谢作者这个软件，挺好用的。

**Comment by wksama** [comment]
感谢支持，后续有什么问题欢迎反馈😏

**Comment by Oays** [comment]
请问下载的壁纸会自动删除吗？
