### ISSUE TITLE
图片是不是又不自动更新了？

### ISSUE THREAD

**Issue by lukegood** [WencoChen/MineEarth#9]
这几天看着一直没有更新。尝试关闭进程又重开无效。后删除了Themes下的壁纸文件，又重启程序，结果仍旧加载回长时间未变的那张图片了。去向日葵官网看了下是在更新的，然后去码云看了下好像没有更新。是不是服务器有问题了呢？

**Comment by wksama** [comment]
感谢反馈。数万次的图片提交导致仓库大小已经超过Gitee限制。正在清理仓库，明天应该就正常了。

**Comment by lukegood** [comment]
已恢复，作者辛苦了~期盼新功能早日上线
